version: '3.9'
services:
  db:
    image: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_DB: mtlist
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - 8080:5432

